name: SOPT Notification Development Server CD

on:    
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create Env File
        env:
          ENV_FILE: ${{ secrets.ENV_DEV }}
        run: |
          touch .env.dev
          echo "$ENV_FILE" >> .env.dev

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy
        run: npm run deploy:dev

